sudo cat /etc/nginx/conf.d/core.conf 
server {
    listen 80;
    server_name crest.deployapp.online www.example.com;

    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl http2;
    server_name crest.deployapp.online www.example.com;

    root /var/www/html/Core_Project;
    index login.php index.php index.html index.htm;

    client_max_body_size 100M;


    ssl_certificate     /etc/nginx/conf.d/fullchain.pem;
    ssl_certificate_key /etc/nginx/conf.d/privkey.pem;

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;

    access_log /var/log/nginx/crest_access.log;
    error_log  /var/log/nginx/crest_error.log;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        include fastcgi_params;

        fastcgi_pass unix:/run/php/php8.5-fpm.sock;

        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }

    location ~ /\.ht {
        deny all;
    }
}
